name: Hugo Build and Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Hugo resources (image processing, etc.)
        uses: actions/cache@v3
        with:
          path: |
            resources/
            .hugo_cache/
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/*.md', '**/*.toml', '**/*.yaml', '**/*.json', 'assets/**/*', 'static/**/*', 'layouts/**/*') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.3'
          extended: true

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Build site
        run: hugo --gc --minify -b https://${{ github.event.repository.name }}.pages.dev

      - name: Deploy with Wrangler
        run: wrangler pages deploy ./public --project-name=${{ github.event.repository.name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
